// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered tool analyzes user data and offers recommendations.
 *
 * - analyzeSpendingHabits - A function that handles the spending analysis process.
 * - AnalyzeSpendingHabitsInput - The input type for the analyzeSpendingHabits function.
 * - AnalyzeSpendingHabitsOutput - The return type for the analyzeSpendingHabits function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeSpendingHabitsInputSchema = z.object({
  transactionHistory: z
    .string()
    .describe(
      'A string containing the user transaction history, with each transaction described with date, category, and amount.'
    ),
});
export type AnalyzeSpendingHabitsInput = z.infer<typeof AnalyzeSpendingHabitsInputSchema>;

const AnalyzeSpendingHabitsOutputSchema = z.object({
  summary: z.string().describe('A summary of the user spending habits.'),
  recommendations: z
    .string()
    .describe('Personalized recommendations for saving money and improving financial health.'),
});
export type AnalyzeSpendingHabitsOutput = z.infer<typeof AnalyzeSpendingHabitsOutputSchema>;

export async function analyzeSpendingHabits(
  input: AnalyzeSpendingHabitsInput
): Promise<AnalyzeSpendingHabitsOutput> {
  return analyzeSpendingHabitsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeSpendingHabitsPrompt',
  input: {schema: AnalyzeSpendingHabitsInputSchema},
  output: {schema: AnalyzeSpendingHabitsOutputSchema},
  prompt: `You are WealthWise's AI assistant, a witty and sharp financial guru who makes managing money fun. Your advice is always on-point and responsible, but you deliver it with a friendly and humorous tone. Analyze the user's spending habits and provide a clever summary and some actionable, fun-to-follow recommendations for saving money.

Transaction History:
{{{transactionHistory}}}

Summary:
{{{summary}}}

Recommendations:
{{{recommendations}}}`,
});

const analyzeSpendingHabitsFlow = ai.defineFlow(
  {
    name: 'analyzeSpendingHabitsFlow',
    inputSchema: AnalyzeSpendingHabitsInputSchema,
    outputSchema: AnalyzeSpendingHabitsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
