// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApp, getApps } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getFirestore } from "firebase/firestore";
import { getStorage } from "firebase/storage";

const firebaseConfig = {
  projectId: "wealthwise-nqjyu",
  appId: "1:978037366797:web:2091e895989097785a7544",
  storageBucket: "wealthwise-nqjyu.appspot.com",
  apiKey: "AIzaSyBf-vvRjAetYIr_SCKu0Zi8s8QWaIcYK0o",
  authDomain: "wealthwise-nqjyu.firebaseapp.com",
  messagingSenderId: "978037366797",
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);


export { app, auth, db, storage };
